"""Builds the CJK font compiled into the WinPE host UI.

The WinPE console host (CtPrep.PeUi) draws its own text with GDI. WinPE images
normally have no FontLink tables, so requesting a face name that exists but has
no CJK coverage (e.g. "Segoe UI") draws every Chinese character as a box. The
fix is to carry our own font and register it privately by name.

The font is linked straight into CTPrep.PeUi.exe (see font_data.c below) instead
of being copied next to it: the payload copy step in startnet.cmd runs on a RAM
disk and any path or ordering mistake there silently brought the boxes back, so
the UI must not depend on a file arriving.

Source: Noto Sans SC, SIL Open Font License 1.1 - free to embed and redistribute,
as installed with Windows. The variable font is pinned to wght=400 (its default
instance is Thin, unusable for a UI) and then subset to the characters the PE can
ever display, so the result stays small enough to link into the executable.

Outputs (both regenerated, not checked in):
    build/pe-font/CTPrep.Font.ttf   the subset font, kept for inspection
    build/pe-font/font_data.c       the same bytes as a C array, linked into the UI

Requires: pip install fonttools

Usage (from the repository root):
    python tools/build-pe-font.py
"""

import io
import os
import re
import sys

SRC_FONT = r"C:\Windows\Fonts\NotoSansSC-VF.ttf"
PE_UI = os.path.join("src", "CtPrep.PeUi", "main.c")
OUTDIR = os.path.join("build", "pe-font")
OUT = os.path.join(OUTDIR, "CTPrep.Font.ttf")
ARRAY = os.path.join(OUTDIR, "font_data.c")

# A private family name so the subset can never collide with a font that happens
# to be installed inside the PE. Must match the name used by main.c.
FAMILY = "CTPrep UI"
SUBFAMILY = "Regular"
FULL_NAME = FAMILY + " " + SUBFAMILY
POSTSCRIPT = "CTPrepUI-Regular"

WEIGHT = 400


def collect_characters():
    """Everything the PE host can put on screen."""
    if not os.path.exists(PE_UI):
        sys.exit("cannot find " + PE_UI + "; run this from the repository root")
    src = io.open(PE_UI, encoding="utf-8").read()
    chars = set()
    for match in re.finditer(r'L"((?:[^"\\]|\\.)*)"', src):
        chars.update(match.group(1))

    # The failure log view echoes deploy.log, which cmd.exe writes in the OEM
    # codepage. Cover all of GB2312 so nothing there can turn into a box.
    for high in range(0xA1, 0xFA):
        for low in range(0xA1, 0xFF):
            try:
                chars.add(bytes([high, low]).decode("gb2312"))
            except UnicodeDecodeError:
                pass

    chars.update(chr(c) for c in range(0x20, 0x7F))
    chars.update("　、。〈〉《》「」『』【】〔〕・ー…‥—–‘’“”※→←↑↓≈≠≤≥×÷±°℃·¥€£§¶†‡•‰′″")
    for drop in "\n\r\t\\\"":
        chars.discard(drop)
    return "".join(sorted(chars))


def rename(font):
    name = font["name"]
    for platform, encoding, language in ((3, 1, 0x409), (3, 10, 0x409), (1, 0, 0)):
        name.setName(FAMILY, 1, platform, encoding, language)
        name.setName(SUBFAMILY, 2, platform, encoding, language)
        name.setName(FULL_NAME, 4, platform, encoding, language)
        name.setName(POSTSCRIPT, 6, platform, encoding, language)
        name.setName(FAMILY, 16, platform, encoding, language)
        name.setName(SUBFAMILY, 17, platform, encoding, language)
        name.setName(POSTSCRIPT + ";CTPrep", 3, platform, encoding, language)


def emit_c_array():
    """Turns the subset font into a C array so it can be linked into the UI."""
    data = open(OUT, "rb").read()
    out = io.StringIO()
    out.write("/* Generated by tools/build-pe-font.py - do not edit.\n")
    out.write(" * Noto Sans SC, SIL Open Font License 1.1 (see PE-UPDATE.md).\n")
    out.write(" * Linked into CTPrep.PeUi.exe so the PE UI never has to find a font file. */\n")
    out.write("\n")
    out.write("const unsigned char kCtPrepFontData[] = {\n")
    for offset in range(0, len(data), 24):
        chunk = data[offset:offset + 24]
        out.write("    " + " ".join("0x%02x," % byte for byte in chunk) + "\n")
    out.write("};\n")
    out.write("\n")
    out.write("const unsigned int kCtPrepFontSize = %d;\n" % len(data))
    io.open(ARRAY, "w", encoding="ascii", newline="\n").write(out.getvalue())
    return len(data)


def main():
    try:
        from fontTools.ttLib import TTFont
        from fontTools.varLib import instancer
        from fontTools import subset
    except ImportError:
        sys.exit("fontTools is required: pip install fonttools")

    if not os.path.exists(SRC_FONT):
        sys.exit("source font not found: " + SRC_FONT)

    text = collect_characters()
    print("characters to keep:", len(text))

    tmp = os.path.join("build", "pe-font-instance.ttf")
    os.makedirs(os.path.dirname(tmp), exist_ok=True)
    chars = os.path.join("build", "pe-font-chars.txt")
    io.open(chars, "w", encoding="utf-8").write(text)

    font = TTFont(SRC_FONT)
    font = instancer.instantiateVariableFont(font, {"wght": WEIGHT}, updateFontNames=True)
    rename(font)
    font.save(tmp)
    print("pinned variable font to wght=%d and renamed it to %s" % (WEIGHT, FAMILY))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    subset.main([
        tmp,
        "--text-file=" + chars,
        "--output-file=" + OUT,
        "--layout-features=",
        "--no-hinting",
        "--name-IDs=*",
        "--name-legacy",
        "--drop-tables+=DSIG,BASE",
        "--recalc-bounds",
        "--recalc-timestamp",
    ])

    for stale in (tmp, chars):
        os.remove(stale)

    check = TTFont(OUT, lazy=True)
    families = {str(r) for r in check["name"].names if r.nameID == 1 and r.platformID == 3}
    size = os.path.getsize(OUT)
    print("wrote %s (%.2f MB)" % (OUT, size / 1048576.0))
    print("glyphs:", len(check.getGlyphOrder()), "| cmap entries:", len(check.getBestCmap()))
    print("family name:", families)
    assert families == {FAMILY}, "family name does not match the name used in main.c"

    emitted = emit_c_array()
    assert emitted == size, "C array size does not match the font file"
    print("wrote %s (%d bytes)" % (ARRAY, emitted))


if __name__ == "__main__":
    main()
