param([string]$Zig = "$PSScriptRoot\compiler\ziglang\zig.exe")
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path -LiteralPath $Zig)) { throw "Portable Zig compiler not found: $Zig" }
$out = Join-Path $repo 'src\CtPrep.PeUi\bin'
New-Item -ItemType Directory -Path $out -Force | Out-Null
# font_data.c is generated by tools/build-pe-font.py and carries the CJK font
# that gets linked into the UI, so no font file has to be copied into the PE.
$sources = @(
    (Join-Path $repo 'src\CtPrep.PeUi\main.c'),
    (Join-Path $repo 'build\pe-font\font_data.c')
)
foreach ($src in $sources) {
    if (-not (Test-Path -LiteralPath $src)) {
        throw "Missing $src - run 'python tools/build-pe-font.py' first (needs fonttools)"
    }
}
$env:ZIG_GLOBAL_CACHE_DIR = Join-Path $repo 'build\zig-cache'
$env:ZIG_LOCAL_CACHE_DIR = Join-Path $repo 'build\zig-local-cache'
& $Zig cc @sources -o (Join-Path $out 'CTPrep.PeUi.exe') -target x86_64-windows-gnu -municode '-Wl,--subsystem,windows' -Os -static -Wall -Wextra -Werror -luser32 -lgdi32 -lshell32 -ladvapi32
if ($LASTEXITCODE -ne 0) { throw "Native UI build failed: $LASTEXITCODE" }
